Write a function to find the longest common substring amongst an array of strings.


referred: https://www.geeksforgeeks.org/longest-common-substring/

## Solution1: Three Nested Loop Using Three Pointers

In [1]:
def longestCommonSubstring(x, y): # O(N^3), assuming that len of two strings are same or similar 
    """
    Input : str; x, y
    Output: str
    
    >>> longestCommonSubstring('abcd', 'abc')
    abc
    >>> longestCommonSubstring('abcd', 'cde')
    cd
    >>> longestCommonSubstring('ab', 'ab')
    ab
    >>> longestCommonSubstring('ab', uo')
    ''
    >>> longestCommonSubstring('abrt', 'qrnt')
    r
    >>> longestCommonSubstring('', '')
    ''
    """
    ## brute force solution; exhastively search for the longest common substring
    # for every char in x, compare with every char in y.
    # if 1st char in x matches with a char in y, pivot at the first x-char and take one baby step 
    #     check 2nd x-char matches with one right next to the y-char
    #         if matches, take one more baby step(nxt incrementation) and repeat comparision 
    #         else, compare 1st x-char with next char in y(yi incrementation)
    # when done comparing 1st x-char with all char in y, repeat the same with 2nd x-char(xi incrementation)
    

    longestLen = 0
    longestStr = ''

    ## xi is slower runner
    for xi in range(len(x)): # O(N)

        ## yi is faster runner 
        for yi in range(len(y)): # O(M)

            cnt = 0
            nxt = 0
            commonStr = ''

            ## take baby step with 'nxt' as long as char in both strings matches 
            while (xi + nxt < len(x)) and (yi + nxt < len(y)) and (x[xi + nxt] == y[yi + nxt]): # O(N or M; which ever that's sorter)
                cnt += 1
                commonStr += y[yi + nxt]
                nxt += 1

            if cnt > longestLen:
                longestLen = cnt
                longestStr = commonStr
                
    return longestStr

__Testing Basecases__

In [2]:
longestCommonSubstring('abcd', 'abc')

'abc'

In [3]:
longestCommonSubstring('abcd', 'cde')

'cd'

In [4]:
longestCommonSubstring('ab', 'uo')

''

In [5]:
longestCommonSubstring('abrt', 'qrnt')

'r'

__Testing Edgecases__

In [6]:
longestCommonSubstring('', '')

''

In [7]:
longestCommonSubstring('ab', 'ab')

'ab'

In [8]:
longestCommonSubstring('abcdej', 'ncwdecr')

'de'

In [9]:
longestCommonSubstring('abqrpcmceectncd', 'rscte')

'ct'

In [10]:
longestCommonSubstring('aaaaaaaaaabbbbbbb', 'aaa')

'aaa'

## Solution2: Dynamic Programming

In [11]:
import numpy as np

In [12]:
def longestCommonSubstring_dp(x, y): # O(N^2), assuming that len of two strings are same or similar
    """
    Input: str; x, y
    Output: str
    """
    
    maxLen = 0
    subTailIdx = 0
    
    # create len(x) x len(y) matrix filled up with zeros
    mtx = np.zeros((len(x), len(y)))
    
    # fill up first col 
    for n in range(len(x)): # O(N)
        if y[0] == x[n]:
            mtx[n][0] = 1
    
    # fill up first row
    for m in range(len(y)): # O(M)
        if x[0] == y[m]:
            mtx[0][m] = 1
    
    # brute-force search: for every char in x, compare with every char in y
    for n in range(1, len(x)):     # O(N)*
        for m in range(1, len(y)): # O(M)
            if x[n] == y[m]:
                mtx[n][m] = mtx[n-1][m-1] + 1
                
                if mtx[n][m] > maxLen:
                    maxLen = int(mtx[n][m])
                    subTailIdx = m
                    
    print mtx    
    return y[subTailIdx - maxLen + 1 : subTailIdx + 1]

__Testing Basecases__

In [13]:
longestCommonSubstring_dp('abcd', 'abc')

[[ 1.  0.  0.]
 [ 0.  2.  0.]
 [ 0.  0.  3.]
 [ 0.  0.  0.]]


'abc'

In [14]:
longestCommonSubstring_dp('abcd', 'cde')

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  2.  0.]]


'cd'

In [15]:
longestCommonSubstring_dp('ab', 'uo')

[[ 0.  0.]
 [ 0.  0.]]


''

In [16]:
longestCommonSubstring_dp('abrt', 'qrnt')

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  0.  1.]]


'r'

__Testing Edgecases__

In [17]:
longestCommonSubstring_dp('', '')

[]


''

In [18]:
longestCommonSubstring_dp('ab', 'ab')

[[ 1.  0.]
 [ 0.  2.]]


'ab'

In [19]:
longestCommonSubstring_dp('abcdej', 'ncwdecr')

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  2.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


'de'

In [20]:
longestCommonSubstring_dp('abqrpcmceectncd', 'rscte')


[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  2.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


'ct'

In [21]:
longestCommonSubstring_dp('aaaaaaaaaabbbbbbb', 'aaa')

[[ 1.  1.  1.]
 [ 1.  2.  2.]
 [ 1.  2.  3.]
 [ 1.  2.  3.]
 [ 1.  2.  3.]
 [ 1.  2.  3.]
 [ 1.  2.  3.]
 [ 1.  2.  3.]
 [ 1.  2.  3.]
 [ 1.  2.  3.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


'aaa'