Find the contiguous subarray within an array (containing at least one number) which has the largest sum.

For example, given the array [-2,1,-3,4,-1,2,1,-5,4],
the contiguous subarray [4,-1,2,1] has the largest sum = 6.

source: https://leetcode.com/problems/maximum-subarray/description/

In [3]:
import numpy as np

In [59]:
def maxSubArray(nums): # O(N^2)
    """   
    Input : list; nums
    Output: int
    
    >>> maxSubArray([-2,1,-3,4,-1,2,1,-5,4])
    6
    >>> maxSubArray([5, 7])
    12
    >>> maxSubArray([5, -3])
    5
    >>> maxSubArray([5, -7])
    5
    >>> maxSubArray([-5, 7])
    7
    >>> maxSubArray([2])
    2
    >>> maxSubArray([-2])
    -2
    >>> maxSubArray([-2, -7])
    -2
    >>> maxSubArray([0])
    0
    """
    
    ARRYLEN = len(nums)
    firstIter = True
    
    # create n x m matrix that's filled with zeros
    mtx = np.zeros((ARRYLEN, ARRYLEN)) # ???? time complexity of this
    
    for n in range(ARRYLEN):        # n-times
        # start each row
        mtx[n][n] = nums[n]
        print mtx
        
        if firstIter:
            maxSum = mtx[n][n]
            subTailIdx = n
            subHeadIdx = n
            firstIter = False
#             print (subTailIdx, subTailIdx)
        
        for m in range(n+1, ARRYLEN): # (n)+(n-1)+(n-1)+ ... + 1 -> n-times
            # recurrsive subproblem rule
            mtx[n][m] = mtx[n][m-1] + nums[m]
            
            if mtx[n][m] > maxSum:
                print 'maxsum:', maxSum
                print 'mtx[n][m]', mtx[n][m]
                maxSum = mtx[n][m]
                subTailIdx = m
                subHeadIdx = n
                print 'maxsum:', maxSum
                print (subTailIdx, subTailIdx)
                
    print mtx
    print "subarry:", nums[subHeadIdx : (subTailIdx + 1)] # O(k)
    return int(maxSum)

__Testing Basecase__

In [ ]:
maxSubArray([-2,1,-3,4,-1,2,1,-5,4])

In [ ]:
maxSubArray([5, 7])

In [ ]:
maxSubArray([5, -3])

In [ ]:
maxSubArray([5, -7])

In [60]:
maxSubArray([-5, 7]) #!!!! 7 

[[-5.  0.]
 [ 0.  0.]]
maxsum: -5.0
mtx[n][m] 2.0
maxsum: 2.0
(1, 1)
[[-5.  2.]
 [ 0.  7.]]
[[-5.  2.]
 [ 0.  7.]]
subarry: [-5, 7]


2

__Testing Edgecase__

In [54]:
maxSubArray([2]) #!!!!

[[ 2.]]
[[ 2.]]
subarry: [2]


2

In [55]:
maxSubArray([-2]) 

[[-2.]]
[[-2.]]
subarry: [-2]


-2

In [56]:
maxSubArray([-2, -7])

[[-2.  0.]
 [ 0.  0.]]
[[-2. -9.]
 [ 0. -7.]]
[[-2. -9.]
 [ 0. -7.]]
subarry: [-2]


-2

In [57]:
maxSubArray([0])

[[ 0.]]
[[ 0.]]
subarry: [0]


0