Find the contiguous subarray within an array (containing at least one number) which has the largest sum.

For example, given the array [-2,1,-3,4,-1,2,1,-5,4],
the contiguous subarray [4,-1,2,1] has the largest sum = 6.

source: https://leetcode.com/problems/maximum-subarray/description/

## Solution1: O(N^2)

In [1]:
import numpy as np

In [2]:
def maxSubArray(nums): # O(N^2)
    """   
    Input : list; nums
    Output: int
    
    >>> maxSubArray([-2,1,-3,4,-1,2,1,-5,4])
    6
    >>> maxSubArray([5, 7])
    12
    >>> maxSubArray([5, -3])
    5
    >>> maxSubArray([5, -7])
    5
    >>> maxSubArray([-5, 7])
    7
    >>> maxSubArray([2])
    2
    >>> maxSubArray([-2])
    -2
    >>> maxSubArray([-2, -7])
    -2
    >>> maxSubArray([0])
    0
    """
    
    ARRYLEN = len(nums)
    firstIter = True
    
    # create n x m matrix that's filled with zeros
    mtx = np.zeros((ARRYLEN, ARRYLEN)) # O(N^2), since it needs to initialize every element to 0
    
    for n in range(ARRYLEN):        # n-times
        # start each row
        mtx[n][n] = nums[n]
        
        # set initial maxSum value
        if firstIter:
            maxSum = mtx[n][n]
            subTailIdx = n
            subHeadIdx = n
            firstIter = False

        # for single item arry or when only very last item is max sum subarray(i.e. [-1, 1, 5, -9, -2, 30])
        if mtx[n][n] > maxSum:
            maxSum = mtx[n][n]
            subTailIdx = n
            subHeadIdx = n
        
        for m in range(n+1, ARRYLEN): # (n)+(n-1)+(n-1)+ ... + 1 -> adding n-times
            # recurrsive subproblem rule
            mtx[n][m] = mtx[n][m-1] + nums[m]
            
            if mtx[n][m] > maxSum:
                maxSum = mtx[n][m]
                subHeadIdx = n
                subTailIdx = m
                
    print mtx
    print "subarry:", nums[subHeadIdx : (subTailIdx + 1)] # O(k)
    return int(maxSum)

__Testing Basecase__

In [3]:
maxSubArray([-2,1,-3,4,-1,2,1,-5,4])

[[-2. -1. -4.  0. -1.  1.  2. -3.  1.]
 [ 0.  1. -2.  2.  1.  3.  4. -1.  3.]
 [ 0.  0. -3.  1.  0.  2.  3. -2.  2.]
 [ 0.  0.  0.  4.  3.  5.  6.  1.  5.]
 [ 0.  0.  0.  0. -1.  1.  2. -3.  1.]
 [ 0.  0.  0.  0.  0.  2.  3. -2.  2.]
 [ 0.  0.  0.  0.  0.  0.  1. -4.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -5. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  4.]]
subarry: [4, -1, 2, 1]


6

In [4]:
maxSubArray([5, 7])

[[  5.  12.]
 [  0.   7.]]
subarry: [5, 7]


12

In [5]:
maxSubArray([5, -3])

[[ 5.  2.]
 [ 0. -3.]]
subarry: [5]


5

In [6]:
maxSubArray([5, -7])

[[ 5. -2.]
 [ 0. -7.]]
subarry: [5]


5

In [7]:
maxSubArray([-5, 7])

[[-5.  2.]
 [ 0.  7.]]
subarry: [7]


7

__Testing Edgecase__

In [8]:
maxSubArray([2])

[[ 2.]]
subarry: [2]


2

In [9]:
maxSubArray([-2])

[[-2.]]
subarry: [-2]


-2

In [10]:
maxSubArray([-2, -7])

[[-2. -9.]
 [ 0. -7.]]
subarry: [-2]


-2

In [11]:
maxSubArray([0])

[[ 0.]]
subarry: [0]


0

In [12]:
maxSubArray([-1, 1, 5, -9, -2, 30])

[[ -1.   0.   5.  -4.  -6.  24.]
 [  0.   1.   6.  -3.  -5.  25.]
 [  0.   0.   5.  -4.  -6.  24.]
 [  0.   0.   0.  -9. -11.  19.]
 [  0.   0.   0.   0.  -2.  28.]
 [  0.   0.   0.   0.   0.  30.]]
subarry: [30]


30

## Solution2: O(n) or Divide and Conquer Approach