Find the contiguous subarray within an array (containing at least one number) which has the largest sum.

For example, given the array [-2,1,-3,4,-1,2,1,-5,4],
the contiguous subarray [4,-1,2,1] has the largest sum = 6.

source: https://leetcode.com/problems/maximum-subarray/description/

## dp Solution1: O(n)

In [1]:
def maxSubArray_linear(nums): # O(N)
    """   
    Input : list; nums
    Output: int, the largest sum
    
    [ Dynamic Programming ]
    Recurrsive subproblem rule: 
        (1) f(n) = f(n-1) + nums[n], if it's > nums[n]
                 = nums[n], otherwise                             
            in this case;
            biggerOfTwo[n] = biggerOfTwo[n-1] + nums[n], if it's > nums[n]
                           = nums[n], otherwise
        (2) Subarray starts from where nums[n] is bigger and ends where the max number in biggerOfTwo is.
    """
    
    biggerOfTwo = [nums[0]]
    # to get maxSum subarray itself
#     maxIdx = 0
#     maxSum = biggerOfTwo[maxIdx]
#     headIdx = 0
    
    # check whether sum of 'f(n-1) + num' is bigger than 'num'
    for idx in range(1, len(nums)):
        num = nums[idx]
        sumOfTwo = biggerOfTwo[idx - 1] + num
        
        # when adding f(n-1) + num is bigger
        if sumOfTwo > num:
            biggerOfTwo.append(sumOfTwo)
            
            # to get maxSum subarray itself
#             if sumOfTwo > maxSum:
#                 maxSum = sumOfTwo
#                 maxIdx = idx
                
        # when a num itself is bigger, starting new subarray from there
        else:
            biggerOfTwo.append(num)
            headIdx = idx
            
            # to get maxSum subarray itself
#             if num > maxSum:
#                 maxSum = num
#                 maxIdx = idx
            
    print biggerOfTwo 
#     print biggerOfTwo[headIdx : maxIdx+1]
    return max(biggerOfTwo)
        

__Testing Basecase__

In [2]:
maxSubArray_linear([-2,1,-3,4,-1,2,1,-5,4])

[-2, 1, -2, 4, 3, 5, 6, 1, 5]


6

In [3]:
maxSubArray_linear([5, 7])

[5, 12]


12

In [4]:
maxSubArray_linear([5, -3])

[5, 2]


5

In [5]:
maxSubArray_linear([5, -7])

[5, -2]


5

In [6]:
maxSubArray_linear([-5, 7])

[-5, 7]


7

In [7]:
maxSubArray_linear([5, -1, -3, 4, -1, 2, 1, -5, 4])

[5, 4, 1, 5, 4, 6, 7, 2, 6]


7

In [8]:
maxSubArray_linear([-2, 0, -2, 4, -1])

[-2, 0, -2, 4, 3]


4

__Testing Edgecase__

In [9]:
maxSubArray_linear([2])

[2]


2

In [10]:
maxSubArray_linear([-2])

[-2]


-2

In [11]:
maxSubArray_linear([-2, -7])

[-2, -7]


-2

In [12]:
maxSubArray_linear([0])

[0]


0

In [13]:
maxSubArray_linear([-1, 1, 5, -9, -2, 30])

[-1, 1, 6, -3, -2, 30]


30

## dp Solution2: O(N^2)

In [14]:
import numpy as np

In [15]:
def maxSumSetter(matrix, row, col):
    maxSum = mtx[n][n]
    subTailIdx = n
    subHeadIdx = n

In [16]:
def maxSubArray(nums): # O(N^2)
    """   
    Input : list; nums
    Output: int, the largest sum
    
    >>> maxSubArray([-2,1,-3,4,-1,2,1,-5,4])
    6
    >>> maxSubArray([5, 7])
    12
    >>> maxSubArray([5, -3])
    5
    >>> maxSubArray([5, -7])
    5
    >>> maxSubArray([-5, 7])
    7
    >>> maxSubArray([2])
    2
    >>> maxSubArray([-2])
    -2
    >>> maxSubArray([-2, -7])
    -2
    >>> maxSubArray([0])
    0
    
    [ Dynamic Programming ]
    Recurrsive subproblem rule:
        (1) Each rows starts at mxt[n][m], where n == m
        (2) f(n, m) = f(n-1, m-1) + nums[m]
            in this case;
            mtx[n][m] = mtx[n][m-1] + nums[m]
        (3) Subarray starts from beginning each row to until where the max sum is
    """

    
    ARRYLEN = len(nums)
    firstIter = True
    
    # create n x m matrix that's filled with zeros
    mtx = np.zeros((ARRYLEN, ARRYLEN)) # O(N^2), since it needs to initialize every element to 0
    
    for n in range(ARRYLEN):        # n-times
        # start each row
        mtx[n][n] = nums[n]
        
        # set initial maxSum value
        if firstIter:
            maxSum = mtx[n][n]
            subTailIdx = n
            subHeadIdx = n
            firstIter = False
            print maxSum, subTailIdx, subHeadIdx

        # for single item arry or when only very last item is max sum subarray(i.e. [-1, 1, 5, -9, -2, 30])
        if mtx[n][n] > maxSum:
            maxSum = mtx[n][n]
            subTailIdx = n
            subHeadIdx = n
        
        for m in range(n+1, ARRYLEN): # (n)+(n-1)+(n-1)+ ... + 1 -> adding n-times
            # recurrsive subproblem rule
            mtx[n][m] = mtx[n][m-1] + nums[m]
            
            if mtx[n][m] > maxSum:
                maxSum = mtx[n][m]
                subHeadIdx = n
                subTailIdx = m
                
    print mtx
    print "subarry:", nums[subHeadIdx : (subTailIdx + 1)] # O(k)
    return int(maxSum)

__Testing Basecase__

In [17]:
maxSubArray([-2,1,-3,4,-1,2,1,-5,4])

-2.0 0 0
[[-2. -1. -4.  0. -1.  1.  2. -3.  1.]
 [ 0.  1. -2.  2.  1.  3.  4. -1.  3.]
 [ 0.  0. -3.  1.  0.  2.  3. -2.  2.]
 [ 0.  0.  0.  4.  3.  5.  6.  1.  5.]
 [ 0.  0.  0.  0. -1.  1.  2. -3.  1.]
 [ 0.  0.  0.  0.  0.  2.  3. -2.  2.]
 [ 0.  0.  0.  0.  0.  0.  1. -4.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -5. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  4.]]
subarry: [4, -1, 2, 1]


6

In [18]:
maxSubArray([5, 7])

5.0 0 0
[[  5.  12.]
 [  0.   7.]]
subarry: [5, 7]


12

In [19]:
maxSubArray([5, -3])

5.0 0 0
[[ 5.  2.]
 [ 0. -3.]]
subarry: [5]


5

In [20]:
maxSubArray([5, -7])

5.0 0 0
[[ 5. -2.]
 [ 0. -7.]]
subarry: [5]


5

In [21]:
maxSubArray([-5, 7])

-5.0 0 0
[[-5.  2.]
 [ 0.  7.]]
subarry: [7]


7

In [22]:
maxSubArray([5, -1, -3, 4, -1, 2, 1, -5, 4])

5.0 0 0
[[ 5.  4.  1.  5.  4.  6.  7.  2.  6.]
 [ 0. -1. -4.  0. -1.  1.  2. -3.  1.]
 [ 0.  0. -3.  1.  0.  2.  3. -2.  2.]
 [ 0.  0.  0.  4.  3.  5.  6.  1.  5.]
 [ 0.  0.  0.  0. -1.  1.  2. -3.  1.]
 [ 0.  0.  0.  0.  0.  2.  3. -2.  2.]
 [ 0.  0.  0.  0.  0.  0.  1. -4.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -5. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  4.]]
subarry: [5, -1, -3, 4, -1, 2, 1]


7

In [23]:
maxSubArray([-2, 0, -2, 4, -1])

-2.0 0 0
[[-2. -2. -4.  0. -1.]
 [ 0.  0. -2.  2.  1.]
 [ 0.  0. -2.  2.  1.]
 [ 0.  0.  0.  4.  3.]
 [ 0.  0.  0.  0. -1.]]
subarry: [4]


4

__Testing Edgecase__

In [24]:
maxSubArray([2])

2.0 0 0
[[ 2.]]
subarry: [2]


2

In [25]:
maxSubArray([-2])

-2.0 0 0
[[-2.]]
subarry: [-2]


-2

In [26]:
maxSubArray([-2, -7])

-2.0 0 0
[[-2. -9.]
 [ 0. -7.]]
subarry: [-2]


-2

In [27]:
maxSubArray([0])

0.0 0 0
[[ 0.]]
subarry: [0]


0

In [28]:
maxSubArray([-1, 1, 5, -9, -2, 30])

-1.0 0 0
[[ -1.   0.   5.  -4.  -6.  24.]
 [  0.   1.   6.  -3.  -5.  25.]
 [  0.   0.   5.  -4.  -6.  24.]
 [  0.   0.   0.  -9. -11.  19.]
 [  0.   0.   0.   0.  -2.  28.]
 [  0.   0.   0.   0.   0.  30.]]
subarry: [30]


30